### ISSUE TITLE
Uploading new version fails to work

### ISSUE THREAD

**Issue by parlough** [SpongePowered/Ore#193]
I was trying to upload a new version of Latch, and I uploaded the jar and the signature. Then when I click the final upload the page sort of refreshes and it prompts me to enter them again just like it did before. Going to the version page I see the update is not there.

Browser & Version: Version 57.0.2975.0 (Official Build) canary (64-bit)

Operating System: Windows 10 Latest

Error message (if applicable): None

Steps to reproduce:

* Go to versions page of a plugin of yours
* Click "New Version"
* Upload jar and signature
* Notice nothing happens when you click upload. Prompts you to upload again.

**Comment by windy1** [comment]
Believe it or not, the error logs reveal that this is actually happening for you for the same reason as https://github.com/SpongePowered/Ore/issues/181 and is because of an underlying issue that only seems to be affecting your project at the moment. Going to close this now but I'll keep the other one open as a reminder to find the underlying issue as well as fix your project.

Basically your project is bugged.
