### ISSUE TITLE
Specify namespace on project creation (for repository resolution)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#23]
The intention is for Ore plugin uploads to hit repo.spongepowered.org and, eventually, be able to be pulled from maven just like a project on Maven Central/etc. For this to work out, we need that namespace and for it to be concrete. Relying on a fully qualified id from the plugin id isn't acceptable (and frankly may be removed soon).

Encourage any and all discussion on the matter.

**Comment by windy1** [comment]
The way I envisioned this is that there could be a "enable maven deployment" in the project settings where you would specify all the options required.

**Comment by Zidane** [comment]
@windy1 

That would work. That would allow the plugin author to have a choice of whether it is available for pull down from repository resolution.

...or do we make that a requirement of putting a project on Ore? Tough question...

**Comment by fdatoo** [comment]
I'm sure that if plugin developers go through the entire process of designing, coding, and deploying a plugin, that they'll be able to supply a fully qualified name, especially considering they already thought of one to give Maven/Gradle. So, having Ore require this in order to put it on the repository is acceptable, if not expected.

**Comment by windy1** [comment]
Going to close this for now. Maven-like integration is definitely planned but the details of implementation cover much more than what is described in this issue.
