### ISSUE TITLE
Cannot save large amounts of markdown to a documentation page.

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#246]
When trying to upload about 140KB of markdown to a documentation page (as I'm trying to create a command reference page for Nucleus on Ore, as you can imagine, there's a lot to add!), I get the following error:

![img](https://i.gyazo.com/9b6c3cd1a2d0eb7f922f0b5f5bca4e2a.png)

[The markdown I've been trying to upload can be found here](https://gist.github.com/dualspiral/5a0685621dc1d9d7cda1d8ab2878d2b3). I can certainly add a subset of it, so I imagine it's a size of page issue (but I cannot be sure of that).

Steps to reproduce:

* Edit a page on Ore
* Add the entirety of the linked markdown
* Attempt to save

**Comment by dualspiral** [comment]
Related: I have also tried to do it with a ~70KB markdown file (this time, a table with my permissions): https://gist.github.com/dualspiral/544778bfd79e327a8f1e40f1284645f2

Attempting to save this file doesn't bring up the unauthorized message, but when the page reloads, it has the old content, not the new.

It should also be noted that the "preview" button works for the permissions file, but not the commands file.

**Comment by stephan-gh** [comment]
There are 3 different limits that are triggered with your markdown page:

- The CSRF check will only parse request bodies up to 100KB. The CSRF token is at the end of the request body so you get `Unauthorized` because it cannot find it. Could be fixed by changing the CSRF token to be included as query parameter (probably better) or extending the buffer limit for the CSRF check using the `play.filters.csrf.body.bufferSize` config property.
- Play will only parse request bodies up to 100KB into the memory, could be changed using `play.http.parser.maxMemoryBuffer`.
- Ore has a limit of 32k characters for each page. (https://github.com/SpongePowered/Ore/blob/master/conf/application.conf.template#L83)

The way it is reported might be a bit confusing. Do we want to increase the limit for the page content, @windy1?

**Comment by windy1** [comment]
@Minecrell The limit for the home page *cannot* be increased because it is based on the Discourse post constraints. We could increase the limit for other pages, but I almost want to say that if your page is that long it should probably be split up into multiple pages anyways.

It's very possible I might have forgotten to add an error message for exceeding the limit however and the body size can be increased well past whatever 32k amounts to so that it's never an issue and we only have to worry about the char count.

**Comment by dualspiral** [comment]
> but I almost want to say that if your page is that long it should probably be split up into multiple pages anyways

I'd honestly be OK with this (I was kind of thinking it myself!) because I'm sure I can adapt to that and split command descriptions into modules, (and just have all the standard commands on their own without all the description), though if the Ore guidelines require me to put all of my content on Ore and not link out to external websites (I know they are still being drafted, so this is just a thought right now) - then this might be a load of pages. I believe there is (currently) only a limit of 10 pages - so that might be hard for me to keep to - but I'll just open another issue for that if/when the times comes.

I _personally_ would like the 70KB permissions table to be on one page, because that's just a huge table, but again, I'm sure that if that's not going to be, then I'll find a way around it. Again, depends on the final guidelines.

All that being said, I agree that the error messages is a more pressing thing.

**Comment by windy1** [comment]
Closed in 984c563e5e025617f023f04f8b544207b5405e90
