### ISSUE TITLE
Add Mixin tag onto Projects

### ISSUE THREAD

**Issue by vectrixdevelops** [SpongePowered/Ore#247]
After reading through https://github.com/SpongePowered/SpongeVanilla/issues/271 I thought I would propose adding a Mixin tag to the project list.

(Example applied to the project "Nucleus Mixins" on Ore)
![example](https://cloud.githubusercontent.com/assets/12867785/24279467/e669ec98-10ae-11e7-8f4f-ac15cd053d98.PNG)

This could be a selective or automatic process by looking at the jars manifest for the relevant Mixin entries on the upload of the plugin.

This would allow server administrators to become aware that the project they're downloading contains a Mixin (reason is defined in the linked issue in SpongeVanilla), though the example I used is very obvious, other cases may not be.

Having this without some kind of explanation is useless, thus this information should be clearly provided in the docs or anywhere else that best fits so that server administrators can clearly understand.

**Comment by vectrixdevelops** [comment]
I think if you hover over the mixin tag it could tell you if it's for "Vanilla", "Forge", "Hybrid" or "Custom"? Not sure what anyone else thinks. 😄

**Comment by ryantheleach** [comment]
The problem is SpongeVanilla, maybe a tag indicating it's compatible with SpongeVanilla and another for SpongeForge is the best way to handle this? Where something tagged with SpongeAPI should work on Lantern theoretically.

Adding onto this, tags relating to server mods vs client mods could be useful as well.

`Server Mod`, `Required Client Mod`, `Optional Client Mod` Seem like decent tags to cover  this.

**Comment by phase** [comment]
The color for the mixin tag displayed there is `#F4803D`

**Comment by phase** [comment]
`META-INF/MANIFEST.MF` will contain

```
Manifest-Version: 1.0
MixinConfigs: mixins.nucleus.invsee.json,mixins.nucleus.worldgen.json
tweakClass: org.spongepowered.asm.launch.MixinTweaker
TweakOrder: 0
FMLAT: nucleus_mixins_at.cfg
ForceLoadAsMod: true
```
