### ISSUE TITLE
Unable to download Plugin

### ISSUE THREAD

**Issue by YOYOK9** [SpongePowered/Ore#258]
I keep getting this error whenever I try to download the Sleepvote plugin:

"Ore is experiencing difficulties.
Unexpected exception[NoSuchFileException: /home/ore/files/plugins/Icohedron/Sleep Vote/sleepvote-0.4.2.jar]"

**Comment by phit** [comment]
bump, this is also a affecting a bunch of other plugins

**Comment by Icohedron** [comment]
I'll link my issue thread here as well. https://github.com/Icohedron/SleepVote/issues/5
Along with my most recent comment:
"I created a whole new PGP key following the guideline that "Ore requires each plugin file (ZIP or JAR) to be uploaded with a detached Pretty Good Privacy (PGP) signature for a public key that is associated with the email that you signed up to Sponge with." I noticed that I had made my PGP key with my alias' email rather than the one I signed up with. So I changed my account's public key a few days ago and just uploaded a new version of the plugin.
But the download is still broken..."

The thing is, the very first upload that I did for the project worked perfectly fine.  It's just all the subsequent ones that didn't work.

**Comment by ryantheleach** [comment]
I've tried uploading the jar for https://ore.spongepowered.org/phit/PrometheusExporter/versions/1.2.0 After phit had tried (using his key) I tried (using my key)

I was able to upload, but the download still isn't available. Not sure if it's a caching issue but it's definitely reproducible for a given jar in production.

**Comment by Grinch** [comment]
@phase Could you take a whack at this?

**Comment by phase** [comment]
Someone needs to check to see if that file exists in prod. My first guess is that it has something to do with a space being in the folder name. There isn't much I can do without knowing the structure on prod.

**Comment by progwml6** [comment]
@phase please discuss this with me on irc/discord and I can check the server

**Comment by leelawd** [comment]
This just started to effect one of my plugins.

I updated 2 of my plugins and uploaded both of them around a minute apart. 1 worked perfectly fine and the other even after attempting to re-upload still has this issue and is showing with:

> Unexpected exception[NoSuchFileException: /home/ore/files/plugins/leelawd93/MMCPrefix/MMCPrefix-1.2.1-API7.jar]


https://ore.spongepowered.org/leelawd93/MMCPrefix/versions/1.2.1

**Comment by phase** [comment]
@leelawd Did you change the names of anything? Plugin ID? Project slug?

Edit: Re-uploading will not fix this bug. It's an issue with the path the file is being stored at.

**Comment by leelawd** [comment]
@phase No, i have not changed anything like that.

**Comment by phase** [comment]
I noticed that MMCPrefix's [plugin id](https://github.com/ModdedMinecraft/MMCPrefix-Sponge/blame/f7bc78dfb5c15b8ffb62848df92da298048267ff/src/main/java/net/moddedminecraft/mmcprefix/Main.java#L28) is `mmcprefix`. The plugin file in prod was stored in `leelawd93/mmcprefix/` instead of `leelawd93/MMCPrefix` because Ore was storing the file in a directory using the _plugin name_ instead of the _project name_.

**Comment by phase** [comment]
The broken versions are still broken, but all new versions will be saved into the proper place. I'm working on a script to fix the old versions.

**Comment by phase** [comment]
I wrote a script to fix the old plugins that are in the in incorrect spots, @progwml6 will be running it sometime within the next couple days. :tada: :tada: :tada: :tada:
