### ISSUE TITLE
Specify source and issues

### ISSUE THREAD

**Issue by kashike** [SpongePowered/Ore#28]
There are `Docs`, `Versions`, and `Discuss` tabs on projects right now, and it would be nice to be able to configure (in project settings, not just at creation time) optional links to a `Source` repository and to an `Issues` manager.

**Comment by windy1** [comment]
I discussed this briefly with @Grinch and my reasoning for not including these tabs was because they aren't really "tabs" of the project since they will take you offsite. I think buttons would be more suited for this.

**Comment by kashike** [comment]
It'd be cleaner as tabs in my opinion. They are large enough things that they should be right up there with versions and discussion/etc - just add a "External link" icon and/or tooltip?

**Comment by windy1** [comment]
It goes against the purpose of tabs though which is navigation within the project. It might look cleaner but when I click a tab I expect that I should be able to navigate away from that tab as well. It's misleading if they are external links.

**Comment by kashike** [comment]
Something like this, then?
![example](http://i.imgur.com/I2UloEZ.png)

**Comment by windy1** [comment]
Yeah probably, but they should probably be `btn-default` and not `btn-primary`.

**Comment by windy1** [comment]
I could also honestly see these being in a single dropdown as well where all the external links would live (source, issues, homepage, etc). If you were planning on implementing this make sure you setup routes to redirects instead of just using the direct link so that I can find the source (if any) for any given project `/<user>/<project>/source` or something as well as including options to specify them during the project creation and in the settings pane. We already pull the project homepage from the plugin meta file even though it's not currently used.
