### ISSUE TITLE
Ore is down

### ISSUE THREAD

**Issue by TheDoctorsLife** [SpongePowered/Ore#31]
http://ore.gratimax.net/ gives a Server Error (500) upon visting.

**Comment by gratimax** [comment]
I was going to create an issue to fix the deployment configuration, but this works as well :stuck_out_tongue:

**Comment by gratimax** [comment]
Perhaps for future reference, the problem lies in how Ore is currently deploying static files and django-compressor. This is a quick screenshot of error info:

![newrelic error](http://puu.sh/hsT6P/834904e228.png)

Possible solutions could be:
1) Use an *actual* static-files solution like deploying to docker and serving with nginx
2) Coerce heroku into doing what I want, i.e. fixing it

**Comment by TheDoctorsLife** [comment]
I like option 2

**Comment by AnUnknownMiner** [comment]
The only real solution I see is the one that will make it work long term and not have any major problems, so probably option 2 based on what you said.

**Comment by Tzky** [comment]
I'd prefer option 3:
code Ore further and fix later.

**Comment by gratimax** [comment]
Honestly, option 1 is more long-term since it mirrors the deployment configuration Ore will eventually have. We will host it on our own (dockerized) infrastructure, Heroku has just been for development. But I do see some use in hosting some sort of instance, since people need to try it out

**Comment by TheDoctorsLife** [comment]
Well, now that you say that, option 1 sounds a whole lot better.

**Comment by gratimax** [comment]
I've since fixed this, the staged instance mostly works (might configure it some more later).
