### ISSUE TITLE
User Ratings / Voting?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#320]
I'd like to see some form of rating system where established users can review Ore plugins.

**Comment by phit** [comment]
Really dislike the idea, feedback can go in the forums, reviews just become outdated quickly, need to be moderated, or are misused for support and feature requests

I know you said `established users` but unless you gonna manually whitelist people to review you will always get crappy reviews.

**Comment by ryantheleach** [comment]
The star system is probably enough then.

**Comment by phit** [comment]
~~Yeah a star system could be nice, I think it should prioritize recent votes though over all time. As plugins improve etc.~~

**Comment by phase** [comment]
There is already a star system in place. What needs to be changed about it?

**Comment by phit** [comment]
didn't even know, ignore me

**Comment by SimonFlash** [comment]
![StarRatings](https://imgs.xkcd.com/comics/star_ratings.png)

I'm personally against a rating system like this because there's way to many problems with doing it in a fair way. I would recommend removing the system entirely and focusing on the like/favorite ratings, but if it must remain then I would suggest the following:

* A rating from months ago should be worth less than a rating from current versions.
* Ratings should be done linked to a specific version.
* Ratings can be displayed overall for general searches, however if any tag filters are used it should use the rating for the recommended build (or latest, if none) available in the search.
* It should be possible to flag reviews for moderation as well as review them. This could be as simple as having a "this helped me 👍" and "this isn't correct 👎" to allowing users to comment on the review itself. In either case, the community should be able to identify inaccurate reviews for the staff.
* Guidelines for reviews should be put in place. A 1 star "does not work on API 7" type of review shouldn't be allowed. Users who repeatedly have poor reviews should not be allowed to give them.

![TornadoGuard](https://imgs.xkcd.com/comics/tornadoguard.png)

**Comment by ryantheleach** [comment]
I'm happy to reject this issue after getting feedback.
