### ISSUE TITLE
Project Submission Changes

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#33]
So I played around with adding a new project and want the following adjusted:
- [x] After you choose a file, either upload it automatically or give me some status of what I've chosen (jar name and file size). Right now I actually waited a sec for some feedback before realizing I need to hit "upload".
- [x] There is no need for the two step process to be constrained to a small rectangle box. Make it a bit bigger so it stands out more
- [ ] This coincides with my other issue about selecting categories and how that shows to the end user but plugins should be able to classify themselves as multiple categories. Set a limit on it if you wish (up to 5?)

**Comment by windy1** [comment]
1. :+1:
2. That panel was originally bigger but I made it smaller because I thought it looked weird -- too much space, too little information. I'll play around with alternate designs regardless.
3. I'm still not sure how I feel about this. Part of me sees your point but the other part of me want to limit it to one category so that people pick the "best" category for their plugin and we don't have people assigning projects to categories where they don't belong for increased exposure.

**Comment by Zidane** [comment]
@windy1 

Regarding 3, that depends...most plugins fall under a singular category but, as an example, my mod Almura touches most of the categories you have (half at the least). I don't think we should let people go and do all the categories but more than 1 would be nice.

**Comment by windy1** [comment]
Maybe we could just add another category for such plugins instead like "General" or something.

**Comment by malte-laukoetter** [comment]
3: i also think that multiple categories are better (but yes it should be limited to something like 3?) because if you search for a e.g. roleplay plugin with some changes to the chat you otherwise need to search the General and the roleplay and the chat category because you don't know what the author has selected. In that case it would also make sense to change the category filter to a and filter instead of an or filter (e.g. all categories should be selected)

**Comment by windy1** [comment]
See @Lergin that's exactly what I'm worried about. Almost all plugins will have "chat" elements to it. If every plugin that changes chat in some way adds the "Chat" category than that category essentially becomes meaningless and not useful at all.

**Comment by windy1** [comment]
@Zidane made some significant changes to the project creator. Let me know what you think:

https://ore-staging.spongepowered.org/new

**Comment by Zidane** [comment]
@windy1 

![new project](https://cloud.githubusercontent.com/assets/744482/14401735/87992eda-fde1-11e5-9672-7b49a9e631ab.PNG)

Make the upload button same size as the label to the left.

**Comment by windy1** [comment]
@Zidane Clear your cache. It looks like this for me in Chrome and FF

![image](http://i.imgur.com/u6Yb9To.png)

**Comment by Zidane** [comment]
False alarm. Damn these browsers...

**Comment by Zidane** [comment]
@windy1 

Maybe write "upload" beside the icon? Would make it immediately clear what it means.

**Comment by windy1** [comment]
Hmm maybe hover text instead? I kind of like the brevity of no text, plus I think it's _fairly_ obvious what the purpose is tbh.

**Comment by Zidane** [comment]
Hover will be fine. Just need some text feedback.

**Comment by windy1** [comment]
@Zidane can this be closed?
