### ISSUE TITLE
Page rendering inconsistences between Github and Ore

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#35]
@windy1 

Unsure if this is github doing it elsewhere but:

Github:
![github](https://cloud.githubusercontent.com/assets/744482/14368885/4349e612-fce6-11e5-9b5a-bb1d4ebe3b35.PNG)

Ore:
![ore](https://cloud.githubusercontent.com/assets/744482/14368887/4a6647c4-fce6-11e5-966c-57bcba3bb34f.PNG)

You should see the differences here. Very nice on the support!

**Comment by Zidane** [comment]
For the non-observant:
- Bolds aren't the same
- No lines being drawn

@windy1 
Unsure about having hyperlinks all being yellow :p

**Comment by Zidane** [comment]
Also just noticed that our spacing is different too.

**Comment by windy1** [comment]
I think I mentioned this in IRC but just to put it out in the public. Ore does not use the same exact markdown rendering as GitHub but rather a similar one with many of the same features. We can tweak it however we like by adding extensions to the `PegDownProcessor` in `models/projects/Page`. Currently all the included extensions are enabled except anchor links because I don't like how they are done in pegdown.

**Comment by Zidane** [comment]
@windy1 

Figured so. The biggest thing we need to do is just make the rendering consistent since it is a royal pain in the ass when you have a github project that is hosted elsewhere and the look is not consistent. Which then leads to maintaining two different markdown looks.

**Comment by MichaelFedora** [comment]
Horizintal line breaks

## 

---

(`-` & `--` vs `---`\+ are apparently different thicknesses on github... huh)

are the biggest gripe for me so far :P Red code is a little weird too, but I like the orange links.
