### ISSUE TITLE
Finalize the navbar with the sister pages

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/Ore#37]
@windy1 

I promise, this is the last of these :).

Docs:

![docs navbar](https://cloud.githubusercontent.com/assets/744482/14373538/ca95e8c6-fd10-11e5-843a-f24efeae13ab.PNG)

Ore:

![ore navbar](https://cloud.githubusercontent.com/assets/744482/14373540/cfa023fe-fd10-11e5-8fc9-7888a2bde916.PNG)
- Drop down icon is different. Position is correct I think

**Comment by windy1** [comment]
~~They are positioned exactly the same for me on my display so I don't think I can really provide a fix for this on yours.~~ 

/me should read things before I respond to them

**Comment by Zidane** [comment]
@windy1 

This is odd, I took the screenshots and upload them here and the Sponge is positioned perfectly. I switch between my browser tabs and yours is off...the only one that isn't out of the three :S.

Regardless, your icon for the drop down is different.

**Comment by Zidane** [comment]
Okay I'm not crazy:

https://www.dropbox.com/s/fbmn8uwdcmqj5mv/Desktop%2004.07.2016%20-%2022.46.50.36.mp4?dl=0

I made a vid for you @windy1 :).

**Comment by windy1** [comment]
That is strange. It shows no difference for me. I'll test it on my widescreen display PC tomorrow.

**Comment by Snowboardpvp** [comment]
I tested it out on two different computers and browsers(1080p), and the ore one is slightly to the right. Slightly nitpicking, but if you are trying to match it perfectly to the forums here are some other errors I found:
- All of the icons in the dropdown are mismatched from the forums.
- It says Docs in the dropdown menu instead of SpongeDocs. I am not sure which one is preferred, but yeah.
- When you are accessing the dropdown on the forums, the top with the logo, "Sponge", and the arrow are highlighted but not in Ore. 
- The dropdown's corners in Ore are squared, not rounded like the ones on the forums, but I believe the squared ones look is nicer due to most aspects of each website being square/rectangular. 
- I am not really sure how to explain it either, but how the top of the dropdown connects to the navbar is different than on the forums.
- Not sure if you are trying to support mobile, but if you make the window small enough and on mobile phones(at least my Nexus 6P on Google Chrome) the Sponge logo/dropdown does not show up at all and seem to be probably somewhere to the left.

**Comment by Zidane** [comment]
@Snowboardpvp 

Those are all valid except for mobile (we're tackling mobile MUCH MUCH later).

**Comment by windy1** [comment]
Paging @lukegb to request font awesome to be used for the navbar chevron

**Comment by lukegb** [comment]
I dislike the FA one. Does FA have any other chevrons?

**Comment by windy1** [comment]
@lukegb The one I'm using now isn't actually FA either it's just bootstraps "caret". Font Awesome [does](http://fortawesome.github.io/Font-Awesome/icon/chevron-down/) have a chevron though.

**Comment by parlough** [comment]
Besides the chevron and a few other icons not matching in the dropdown, a blackened background as you hover over the Sponge logo and a white one as you hover over your user icon would bring the navbar in line with the one on the forums for the most part. The color used for the search(magnifying glass) and the "New Project" button also differ from the color of similar aspects on the forums and docs. It is much more orange on ore than it should be.

**Comment by windy1** [comment]
Superseded by https://github.com/SpongePowered/Ore/issues/73
