### ISSUE TITLE
Cannot name two pages with the same heading

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/Ore#421]
When adding a new page as a sub page, it cannot have the same name as another page that is a parent page.

Steps to reproduce:

* Step 1 Add a parent page, say, `Modules`
* Step 2 To that parent page, add `Home`

You'll get the editor for the `Home` page, when you wanted a new page under `Modules/Home`

**Comment by Ewoutvans** [comment]
If we want to allow this we need to redesign the URL scheme or do like the forums and append the page number.
So instead of
`/Nucleus/Nucleus/pages/Admin`
do
`/Nucleus/Nucleus/pages/Admin-531` 
But this introduces the problem of linking to other pages because the numbers are not known before publishing

Or we could do
`/:author/:slug/pages/:parent/:child`

Both solution are breaking changes and need further discussion maybe this should be pushed back to 1.7.0

**Comment by mbax** [comment]
I'd vote for the second strategy. Looks prettier! :D

**Comment by progwml6** [comment]
I prefer the second one, and would rather avoid breaking apis right now

**Comment by progwml6** [comment]
this will get done with various other wiki changes in 1.7
