### ISSUE TITLE
Releasing multiple identical plugin versions for different API

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#431]
Reported by eufranio in discord.

They were expecting to be able to upload multiple plugins with the same version string, that is made for different API versions.

Should we allow this? What should the recommended practice be?

**Comment by Eufranio** [comment]
Simon: `better solution is to have jars attached to versions rather than versions attached to jars`. I agree with that, Ore could have a version system like Curse, where there's one main jar (or just the version, no main jar), and we can upload more files tied to this specific version. That way we could have like a `1.0.0` version with multiple jars, for supported API versions by example, or sources, deobf jars, etc.

**Comment by dualspiral** [comment]
See https://github.com/SpongePowered/Ore/issues/366

**Comment by progwml6** [comment]
Any further feedback on this should be in #366
