### ISSUE TITLE
Soft delete warning a bit too harsh

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#453]
"Once you delete a project, it cannot be recovered." for soft delete is a bit inaccurate (I hope!).

**Comment by mbax** [comment]
While I'm at it, "You have send the project for review" - should be "sent"

**Comment by simon816** [comment]
I think delete should be treated as final. Even if it's still recoverable I'd say the project contents goes into an undefined state, where we may or may not keep it for some length of time.
We don't want to have unnecessary administration effort because someone knows it can be un-deleted.
We may also want the flexibility to have "delete means delete" sometime in the future

**Comment by mbax** [comment]
> We don't want to have unnecessary administration effort because someone knows it can be un-deleted.

Since the only folks that can access it is me and other leadership, I'm not worried. If people start treating it like a toy I'll just start taking extra long to undelete. I'd rather it be something to possibly screw up without causing a panic attack.

> We may also want the flexibility to have "delete means delete" sometime in the future

No! :(

**Comment by Ewoutvans** [comment]
@mbax any suggestions for the new message?

**Comment by mbax** [comment]
Something along the lines of "Only do this if you are certain!" - implying a bad idea to play with but not implying actually deleting all records. Would like input on better phrasing.

**Comment by Grinch** [comment]
I am in agreement with simon816 on this, treat soft deletes as 'final' and recovery becomes a 'best effort' sort of affair.
