### ISSUE TITLE
Agree to ToS prior to uploading

### ISSUE THREAD

**Issue by kashike** [SpongePowered/Ore#487]
`15:38:13 kashike | Well, I was thinking it'd be good to have a pre-upload: "Before uploading ... you must read and agree to the [Ore Terms of Service](link). [I Agree] [Get Me Out Of Here]`

**Comment by Faithcaio** [comment]
Could be annoying if it comes up as a separate screen every time.
So maybe instead on the last page put smth like.
By pressing "Publish" you agree to the Ore Terms of Service etc...

**Comment by kashike** [comment]
That's basically what I mean, buttons are just an example :3

**Comment by dualspiral** [comment]
Maybe make it a dialog before first upload, and then any time the ToS changes?

**Comment by phase** [comment]
I like the "text above the upload button linking to the TOS" idea. It's simple.

**Comment by dualspiral** [comment]
I like it too, but you want to ensure two things:

* That we have _explicity_ showed them that they _must_ agree to the ToS so no-one has the excuse "well, the link wasn't big enough", because we shove it in their faces
* That if we make a change, uploaders get a reasonable notice that it's changed (even though we say that we may make a change without warning, this way, we _tell_ people) it's changed

That's why I think we need the dialog box, logging when someone last agreed in a database and adding a "reset" button on an admin panel somewhere that allows mbax to say "we made a change, show the message to everyone again".

It just gives us the recourse to say "we told you so" because someone explicity agreed - if they didn't read it, that's their problem.

**Comment by felixoi** [comment]
Do we need to know who agreed the ToS? Otherwise a cookie would be enough for checking if ToS was updated.

**Comment by dualspiral** [comment]
Yes. We need to record this agreement because doing so will give us a legal footing should some issue arise. Using a cookie is not sufficient, especially for those who use browsers with cookies disabled (they do exist), as the UX will become dire.

Quite simply, **we should not cut any corners when it comes to displaying and inviting acceptance of our ToS and project guidelines**, and I'm worried that's what is going to happen here. This is one area where simple, easy solutions do not cut it. The ToS needs to be displayed explicitly and we should have record of a users acceptance of it in order to be able to defend ourselves in any dispute - a major rule is to **never trust the client**, storing it in a cookie is exactly that.

As a result, note that the API should refuse to function unless the ToS is accepted for the account in question. That in itself requires a server side check.

I would like to point out that the ToS does apply to all Sponge services, so there should be some mechanism to ensure all users get that. However, Ore has the additional burden of the project guidelines - acceptance of this perhaps should be part of this issue too.

**Comment by gabizou** [comment]
Not to mention that the forums should have a similar accept tos flag. Would it make sense to have the flag through SpongeAuth, such that it is a global flag to be able to check no matter what web service is being visited and authenticated with?

**Comment by phase** [comment]
Closed with https://github.com/SpongePowered/SpongeAuth/pull/186
