### ISSUE TITLE
Trusted Developer Submission Approval Exemption

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Ore#493]
We probably shouldn't waste time approving plugin downloads for developers we know are trustworthy.  Developers like myself, dualspiral and Luck are clearly not going to upload malicious files. Any plugin created by these "trusted" developers probably should be exempt from the submission approval process.

However, Project approval should always happen. So if a trusted developer decides to create a new project on Ore, the standard approval process should be done. Once approved, the trusted developer no longer needs approval for their submissions.

**Comment by progwml6** [comment]
I’d recommend setting it to require periodic reviews of new files every 3-6 months from such projects and that api returns show that they are trusted, and if they were reviewed or not

**Comment by bloodmc** [comment]
Sure that sounds reasonable.

**Comment by phase** [comment]
I don't like this. I think no one should be "above the law" and every version should go through the approval process.

If you account gets compromised, then we have versions that are marked as _"safe to download"_ that have been approved by _no one_, and that's not good.

What if an accidental exploit goes in that the approver catches? Then there's another layer of safety between plugin developer and the plugin consumer. "Trusted" food companies still have to wait for the FDA to approve their items. "Trusted" plugin developers should also have to be approved.

---

If we are to approve this, I'd like to schedule this for [v1.8](https://github.com/SpongePowered/Ore/milestone/7).

**Comment by bloodmc** [comment]
Trusted developer accounts would be required to use 2FA. If you make the submission process tedious as it is now then many plugin devs won't bother uploading many development builds assuming they are pushing a lot of commits.

A better solution would be supporting github builds that would automatically get uploaded to ore exactly as we do with jenkins. Forge already supports a few mods on their jenkins whom they "trust". We could do the same with Ore.

**Comment by phase** [comment]
Automatic uploads sound good but automatic approval dosen't. And just because _every development build_ isn't approved doesn't mean _people can't download it._ I view the "approved" state as _"out team has reviewed this item and we deem it safe"_, not _"we trust this guy so he's probably giving you something safe"_.

**Comment by bloodmc** [comment]
`And just because every development build isn't approved doesn't mean people can't download it.`

Yes, but to have every single build I upload get the message `This version has not been reviewed by our moderation staff and may not be safe for download!` gets a bit annoying.

As for automatic builds, if this becomes a feature then my issue would still stand as far as approvals go. Would automatic builds uploaded to Ore require approval?

**Comment by bloodmc** [comment]
Closing as this can be discussed internally.

**Comment by phase** [comment]
> `This version has not been reviewed by our moderation staff and may not be safe for download!` gets a bit annoying.

This message is true, though, and I think that it is good to warn our users if _we haven't reviewed an item_ that we _haven't reviewed it._ Our review team is there to review, and I don't want to remove the message saying _"our review team hasn't reviewed this"_ if they _haven't review it_.

I understand that it is annoying to have this "warning" on your download that _you_ know is safe, _the review team_ knows is safe, and _the Sponge community_ may think is safe, but the purpose of the review team is to really _confirm_ to all users that we _"deem this download **safe**."_ The very _last_ thing I want is to have a user complain that a download _wasn't safe_ when we could have prevented it.

I have trust in @mbax's review team, because these are people that have been _deemed safe_, but I would never trust a review team member approving their own plugin. Just like how we approve PRs here and require at least one team member to approve the changes. We all have push access, but that extra layer of safety is an important measure.

Edit: oof I was typing this out, we can talk on voice this weekend
