### ISSUE TITLE
Provide warning when renaming projects that it will not affect the pluginid

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Ore#551]
Browser & Version: `Edge 42.17134.1.0` `EdgeHTML 17.17134`
Operating System: `Windows 10 x64`

I have renamed one of my projects from `AntiXray` to `Mirage` but now I have two issues:
- I can't upload new versions of my plugin. I'm getting this error message: "The uploaded plugin ID must match your projects plugin ID."
- The API hasn't been updated. I still need to use https://ore.spongepowered.org/api/projects/antixray/versions?offset=0 to list versions instead of https://ore.spongepowered.org/api/projects/mirage/versions?offset=0 .

**Comment by phase** [comment]
Internally, renaming your project only renames the display name and not the internal name. This creates the side effects you listed.

I’m going to have to forward this to @mbax to see what his opinion is on renaming projects. If you were to change the plugin’s internal ID, then all the previous versions of the plugin would contain an invalid ID. My belief was that internal plugin IDs should never change, even if you change the name of your plugin.

**Comment by Yeregorix** [comment]
I understand. Should I recreate a new project with the new id ?

**Comment by Yeregorix** [comment]
As a temporary (or final?) solution, I renamed my project back to its previous name and created a new one with the new name.

**Comment by phase** [comment]
I believe this should be the course of action when completely renaming a project. If upstairs wants to comment I’ll let them.

**Comment by Yeregorix** [comment]
Finally, I recognize that it's better that way. However, I think a little message next to the rename button to indicate that changing the name does not mean changing the identifier could be nice.

**Comment by ryantheleach** [comment]
As an alternative, could we (warn users) then archive the older project somehow, and have the new project link to the previous one for older versions?

**Comment by phase** [comment]
Our current dependency system will give links to projects that match the `id` in the dependency. This works because projects and their mod IDs are tied together. If we want to change that, which I think a lot of people would enjoy, we need to rethink how the dependency system grabs dependencies. Here's my proposal.

When you upload a version, the dependency IDs are stripped out and matched with projects across the database. If we match only against versions, then we can filter using the dependency version too and provide a direct link to the version's download page. If multiple versions match, we could leave all the ones that match in a "suggestion" state. If an admin of the project views the project page, they can confirm which one they want. Otherwise, the version that matches could automatically be confirmed (this might be bad in case a malicious user makes a fake version in their project to phish downloads).

IDs that are platforms (`sponge`, `forge`, `spongeforge`, etc) will _not_ be allowed on Ore. These are automatically handled by the system already.

**Comment by Katrix** [comment]
This will likely not happen. We've talked about it many times, and it will likely just bring a lot of complications. There is also the fact as pointed out above that the plugin id is part of the API, and that won't change at least until some hypothetical API V3.

We'll likely just go with the original idea of providing a bigger warning that the two names are separate.

**Comment by Katrix** [comment]
Fixed by #976
