### ISSUE TITLE
Plugin review system

### ISSUE THREAD

**Issue by humaidq** [SpongePowered/Ore#65]
[There is a thread about this already](https://forums.spongepowered.org/t/plugin-hosting/1150), it asked people which kind of plugin reviewing system they preferred. Should ore also include a plugin review system before the file goes live? Or many suggestions said that it should warn users if they are downloaded an unverified file (which might fit in Sponges open nature) and have community reviewed option (may be a good idea, but I am not sure how that will be done).  
Proposal 3 suggests decompiling bytecode and checking for any suspicious code or pattern. But I strongly dislike the "After the first file, all files are immediately available for download" idea. Should we have a combination all?

**Comment by kmecpp** [comment]
I think a combination of the many suggested ideas is really the only option that even makes sense. The real question should be where along the spectrum of SLOW+SAFE (e.g. Bukkit) to FAST+RISK (Spigot) Sponge should aim for.

I suppose ideally, at least in my opinion, the goal should be to make the plugin base as safe as possible without sacrificing any speed for the vast majority of plugin developers. After browsing through many of the comments on the linked thread and combining some ideas with Proposal 3, I came up with the following proposal which I expect to change with more input.

**Tentative Proposal:** (Disclaimer: There isn't much logical order to this list)
- Both scan and manually review the first submission of each developer
- Scan all uploads from all developers
- Put flagged files in a priority queue for manual review
- An advanced reputation system (vague, I know) that uses a plugin developers reputation, determined by plugin downloads, forum activity, etc..., as well as the popularity of their plugin(s) to determine what priority to give to flagged plugins they may submit and how many reports needed to restrict download access for their plugin(s).
- A very informative display/notification (icons for plugin downloads) system for users so that they can easily judge the reputation of a plugin (include: downloads, plugin rating, developer reputation, its level of review: none, community reviewed, staff reviewed, flags (if any) detected by scanner etc..)
- Make all submissions available for download, given the user is informed of the level of review, and reputation of the plugin.
- A separate community review system, similar to StackExchange's for plugins to gain some reputation without the need of an official review. Reviewers could get credit or rewards for reviewing _competently_ (This should be restricted to trusted users and also contain security checks for people you not reviewing carefully and/or competently)
- If a plugin is reported once, add it to the manual review queue with high priority but do not restrict download access
- If a plugin is reported multiple times (By different IPs) temporarily restrict download access and put the plugin at the top of the manual review queue.
- Report button for both the plugin and individual files
- Permanently ban anyone who attempts to, or has uploaded plugins with malicious intent
- Others? Changes?

<br>
A few other ideas I would also like to mention,

I like the idea of uploading the source code for the plugins to Ore to avoid the need for decompiling the code and the security issues that come with that, but I don't really see how that would work smoothly with plugins' dependencies, and even if that was managed, how much would it hinder plugin deployment for the developer?

It might also be an option to track everyone who downloads plugin to immediately send them an email (or some other notification) if that plugin was found to contain malicious code. A problem I could see with that however is that amount of data that would have to be stored in order to do that. Tens of thousands or even millions of emails/accounts for each plugin, although I guess you could only do that for people who are logged in. As an alternative, it would be possible to build a defense mechanism directly into the implementation of Sponge which displays a warning in the console and/or stops the server if any of the plugins are found on a blacklist, but that's a tad far fetched and I would only see a need for it in extreme cases.

**Comment by ryantheleach** [comment]
The only part I have problem with is the gamification of the community review. gamification needs to be handled very carefully or else it can lead to very dodgy circumstances.

> . As an alternative, it would be possible to build a defense mechanism directly into the implementation of Sponge which deletes any plugins found on a blacklist, 

Warn the admin, prevent server start.  Don't delete automatically.

**Comment by humaidq** [comment]
@kmecpp 
Your proposal is very identical if not exactly the same what I was thinking about a few days ago, I just did not have time to write it. The reputation system also can be linked with the forums (if he is a regular for example) and maybe even vice-versa (if discourse allows). The detector should have detection levels, something like when Bukkit Dev files had the `semi-normal` status (which in my experience, Bukkit's detection system is not that accurate).
I had the idea about letting Ore compile the sources, it will make it slightly harder for devs to get it uploaded and make it a load on Ore to compile jars. It will probably drastically reduce low-effort plugins, but I still don't think it is practical especially for closed-source freeware projects. I support the idea of having a community reputation system which is separate, it might help catch things that are not found by staff. And about the warning notification if someone uses a plugin with dangerous code, Sponge implementation should check all plugins against Ore (for updates, metrics and status). Deleting is always a bad idea, and it violates my rule of "Never delete any file (with few exceptions of course)." I think it is a good idea to prevent users not logged in from downloading unverified files, and giving a big red warning to logged in users.

Having a community review option is great, but I am not sure if people would actually decompile the plugin rather than "I like this plugin, let me vote it as safe!" But when voting, it should remind people that they must already viewed the decompiled bytecode. But I don't know if encouraging people to decompile plugins is a good idea either, because that's what the community review option is making people do.

**Comment by ryantheleach** [comment]
> But when voting, it should remind people that they must already viewed the decompiled bytecode

Or show them the decompiled code in the browser.

> But I don't know if encouraging people to decompile plugins is a good idea either, because that's what the community review option is making people do.

Absolutely the more eyes the better. Honestly I'd prefer it if you couldn't have closed source plugins on Ore. If you are sharing the binaries, why not share the source.

**Comment by windy1** [comment]
Handled in 746dc3b6fa3654b217c39a6a6120718890db808a
