### ISSUE TITLE
Plugin download link for copying doesn't exist

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Ore#743]
![bildschirmfoto vom 2019-02-08 01 27 13](https://user-images.githubusercontent.com/10366256/52451784-ae14a280-2b40-11e9-834e-2435b2a06d0f.png)

"Copy URL" yields to https://ore.spongepowered.org/RandomByte/PokeBattleClauses/versions//download

which then is

![bildschirmfoto vom 2019-02-08 01 28 21](https://user-images.githubusercontent.com/10366256/52451830-d9978d00-2b40-11e9-9655-f3b0b737a89e.png)

Edit: Only affects https://ore.spongepowered.org/RandomByte/PokeBattleClauses

**Comment by ghost** [comment]
Caused by not having a recommended build. Is resolved for this case, but seems to be happening a lot. I do not see a relevant issue elsewhere in Ore, so am unsure if that has been officially reported or fixed yet.

Please close this issue if it's not relevant.

Mostly Fixed in:
PR #735 - Commit c81e168
