### ISSUE TITLE
Allow downloading a plugin as a jar

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/Ore#94]
Currently, Ore packages a version in a zip file when it is uploaded. While this can be a useful option to have, it can becoming very irritating to repeatedly unzip these files. Ore should have an option to download a version directly, in addition to having it packaged in a zip.

**Comment by Aaron1011** [comment]
I'll be implementing this.

**Comment by stephan-gh** [comment]
@Aaron1011 Any news for this issue?

**Comment by stephan-gh** [comment]
To be honest, I'm not sure about a use case for wrapping a single plugin JAR in an additional ZIP (when the JAR is already a compressed ZIP). It will always just cause additional work for the user to install the plugin that can be also confusing because you can't just drop the plugin into your `mods` folder.

**Comment by JBYoshi** [comment]
Branch: [`uploads`](https://github.com/SpongePowered/Ore/tree/uploads)

**Comment by windy1** [comment]
Merged and resolved.
